mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path("", views.index, name="index"),
    path("new/", views.new, name="new"),
    path("create/", views.create, name="create"),
    path("<int:question_id>/", views.detail, name="detail"),
    path("<int:question_id>/results/", views.results, name="results"),
    path("<int:question_id>/vote/", views.vote, name="vote"),
]

polls/models.py
import datetime

from django.db import models
from django.utils import timezone

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text
    
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

polls/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse
from .models import Question, Choice
from django.utils import timezone

from .models import Question

def new(request):
    return render(request, 'polls/new.html')

def create(request):
    new_poll = Question()
    new_poll.question_text = request.POST['title']
    new_poll.pub_date = timezone.now()
    new_poll.save()

    new_choice_one = Choice()
    new_choice_one.question = new_poll
    new_choice_one.choice_text = request.POST['select_one']
    new_choice_one.votes = 0
    new_choice_one.save()

    new_choice_two = Choice()
    new_choice_two.question = new_poll
    new_choice_two.choice_text = request.POST['select_two']
    new_choice_two.votes = 0
    new_choice_two.save()

    return redirect('polls:detail', new_poll.id)



def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    template = loader.get_template('polls/index.html')
    context = {
        'latest_question_list': latest_question_list,
    }
    return render(request, 'polls/index.html', context)

def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/detail.html', {'question': question})

def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/results.html', {'question': question})

def vote(request, question_id):
    # return HttpResponse("You're voting on question %s." % question_id)
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExixt):
        return render(reqeust, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes = 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

polls/templates/polls/detail.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>detail page</title>
  </head>
  <body>
    <h1>{{ question.question_text }}</h1>

    {% if error_message %}
    <p><strong>{{error_message }}</strong></p>
    {% endif %}

    <form action="{% url 'polls:vote' question.id %}" method="post">
      {% csrf_token %} {% for choice in question.choice_set.all %}
      <input
        type="radio"
        name="choice"
        id="choice{{ forloop.counter }}"
        value="{{ choice.id }}"
      />
      <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label
      ><br />
      {% endfor %}
      <input type="submit" value="Vote" />
    </form>
    <a href="{% url 'polls:index' %}">Go to test sheet</a>
  </body>
</html>

polls/templates/polls/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>index page</title>
  </head>
  <body>
    <a href="{% url 'polls:new' %}"><button>문제 출제하기</button></a>
    <hr />

    <h1>문제 목록</h1>
    {% if latest_question_list %}
    <ul>
      {% for question in latest_question_list %}
      <li>
        <a href="{% url 'polls:detail' question.id %}"
          >{{question.question_text}}</a
        >
      </li>
      {% endfor %}
    </ul>
    {% else %}
    <p>No polls are available.</p>
    {% endif %}
  </body>
</html>

polls/templates/polls/new.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>create page</title>
  </head>
  <body>
    <h1>문제 만들기</h1>
    <form action="{% url 'polls:create' %}" method="POST">
      {% csrf_token %} 문제 질문 작성 <input type="text" name="title" />
      <br />
      정답 선지 작성 <input type="text" name="select_one" /> <br />
      오답 선지 작성 <input type="text" name="select_two" /> <br />
      <input type="submit" value="등록" />
    </form>
  </body>
</html>

polls/templates/polls/results.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>result page</title>
  </head>
  <body>
    <h1>{{ question.question_text }}</h1>

    <ul>
      {% for choice in question.choice_set.all %}
      <li>
        {{ choice.choice_text }} -- {{ choice.votes }} vote{{
        choice.votes|pluralize }}
      </li>
      {% endfor %}
    </ul>

    <a href="{% url 'polls:detail' question.id %}">Vote again?</a>
    <a href="{% url 'polls:index' %}">Go to test sheet</a>
  </body>
</html>